### ISSUE TITLE
상황별 되돌리기

### ISSUE THREAD

**Issue by h-sick** [h-sick/gitflow-teamstudy#3]
- [ ] staging 되돌리기
- [ ] 직전 commit 변경하기
- [ ] commit revert하기

**Comment by minsoftk** [comment]
제가 이슈를 만들어야 되는거 아닌가요?

**Comment by h-sick** [comment]
> 제가 이슈를 만들어야 되는거 아닌가요?

아 그런가요? 제가 만들어야 되는 줄 알았어요.

**Comment by h-sick** [comment]
이슈 잘못 생성하여 삭제하겠습니다.
